version: 2
jobs:
  build:
    branches:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/ezbuy/redis-orm
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - install
      - run: make buildTpl
      - run: make install
      - test
      - run: redis-orm code -i ./example/yaml/ -o ./example/model/
      - run: go test -v ./orm/sqlbuilder
